### ISSUE TITLE
Polyserve exits with cryptic error when two instances are running

### ISSUE THREAD

**Issue by arthurevans** [PolymerLabs/polyserve#21]
Not sure whether there's an issue with the setup of neon-animation -- there were a couple of missing files. But if that's the case, the error could be more helpful.

Repro:

git clone neon-animation
bower install
polyserve

```
Starting Polyserve on port 8080
Files in this directory are available at localhost:8080/components/neon-animation/...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.app.listen (/Users/arthure/npm-packages/lib/node_modules/polyserve/node_modules/express/lib/application.js:595:24)
    at Object.startServer (/Users/arthure/npm-packages/lib/node_modules/polyserve/src/start_server.js:28:16)
    at /Users/arthure/npm-packages/lib/node_modules/polyserve/bin/polyserve:19:13
    at /Users/arthure/npm-packages/lib/node_modules/polyserve/node_modules/resolve/lib/async.js:46:14
    at process (/Users/arthure/npm-packages/lib/node_modules/polyserve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/arthure/npm-packages/lib/node_modules/polyserve/node_modules/resolve/lib/async.js:188:17)
```

**Comment by atotic** [comment]
Are you running polyserve in another window?

**Comment by arthurevans** [comment]
Ack. Apparently that is the case. Should've seen that it was failing on a listen().

Yeah, DEFINITELY need a better error message here. 

Is there an option to run polyserve on a different port?

**Comment by LM450N** [comment]
Despite the [code to manage this issue](https://github.com/PolymerLabs/polyserve/commit/4758d6e4e0ac1925f0b770305546097862fa743a#diff-466c359bc2d27f93e5d4d08008448238R35) I have got the following error.

![screenshot 2015-07-22 at 23 39 40](https://cloud.githubusercontent.com/assets/2325091/8838478/1f8d867e-30cd-11e5-898c-91de4b7257c0.png)

**Comment by justinfagnani** [comment]
Is anyone still hitting this issue? I've tried launching multiple polyserve instances recently and get the proper error message.
